
/* Metrics
aws.natgateway.active_connection_count
aws.natgateway.bytes_in_from_destination
aws.natgateway.bytes_in_from_source
aws.natgateway.bytes_out_to_destination
aws.natgateway.bytes_out_to_source
aws.natgateway.connection_attempt_count
aws.natgateway.connection_established_count
aws.natgateway.error_port_allocation
aws.natgateway.idle_timeout_count
aws.natgateway.packets_drop_count
aws.natgateway.packets_in_from_destination
aws.natgateway.packets_in_from_source
aws.natgateway.packets_out_to_destination
aws.natgateway.packets_out_to_source
*/
