# Look at existing integration dashboard
/* Metrics
aws.elasticache.bytes_read_into_memcached
aws.elasticache.bytes_used_for_cache
aws.elasticache.bytes_used_for_cache_items
aws.elasticache.bytes_used_for_hash
aws.elasticache.bytes_written_out_from_memcached
aws.elasticache.cache_hits
aws.elasticache.cache_misses
aws.elasticache.cas_badval
aws.elasticache.cas_hits
aws.elasticache.cas_misses
aws.elasticache.cluster_count
aws.elasticache.cmd_config_get
aws.elasticache.cmd_config_set
aws.elasticache.cmd_flush
aws.elasticache.cmd_get
aws.elasticache.cmd_set
aws.elasticache.cmd_touch
aws.elasticache.cpuutilization
aws.elasticache.curr_config
aws.elasticache.curr_connections
aws.elasticache.curr_items
aws.elasticache.decr_hits
aws.elasticache.decr_misses
aws.elasticache.delete_hits
aws.elasticache.delete_misses
aws.elasticache.engine_cpuutilization
aws.elasticache.evicted_unfetched
aws.elasticache.evictions
aws.elasticache.expired_unfetched
aws.elasticache.freeable_memory
aws.elasticache.get_hits
aws.elasticache.get_misses
aws.elasticache.get_type_cmds
aws.elasticache.hash_based_cmds
aws.elasticache.incr_hits
aws.elasticache.incr_misses
aws.elasticache.is_master
aws.elasticache.key_based_cmds
aws.elasticache.list_based_cmds
aws.elasticache.network_bytes_in
aws.elasticache.network_bytes_out
aws.elasticache.new_connections
aws.elasticache.new_items
aws.elasticache.node_count
aws.elasticache.reclaimed
aws.elasticache.replication_bytes
aws.elasticache.replication_lag
aws.elasticache.save_in_progress
aws.elasticache.set_based_cmds
aws.elasticache.set_type_cmds
aws.elasticache.sorted_set_based_cmds
aws.elasticache.string_based_cmds
aws.elasticache.swap_usage
aws.elasticache.touch_hits
aws.elasticache.touch_misses
aws.elasticache.unused_memory
*/

