# Look at existing integration dashboard
/* Metrics
aws.elb.active_connection_count
aws.elb.backend_connection_errors
aws.elb.client_tlsnegotiation_error_count
aws.elb.consumed_lcus
aws.elb.estimated_albactive_connection_count
aws.elb.estimated_albconsumed_lcus
aws.elb.estimated_albnew_connection_count
aws.elb.estimated_processed_bytes
aws.elb.healthy_host_count
aws.elb.healthy_host_count_deduped
aws.elb.healthy_host_count.maximum
aws.elb.healthy_host_count.minimum
aws.elb.httpcode_backend_2xx
aws.elb.httpcode_backend_3xx
aws.elb.httpcode_backend_4xx
aws.elb.httpcode_backend_5xx
aws.elb.httpcode_elb_4xx
aws.elb.httpcode_elb_5xx
aws.elb.httpcode_target_2xx
aws.elb.httpcode_target_3xx
aws.elb.httpcode_target_4xx
aws.elb.httpcode_target_5xx
aws.elb.latency
aws.elb.latency.maximum
aws.elb.latency.minimum
aws.elb.latency.p95
aws.elb.latency.p99
aws.elb.new_connection_count
aws.elb.processed_bytes
aws.elb.request_count
aws.elb.request_count_per_target
aws.elb.surge_queue_length
aws.elb.target_response_time.average
aws.elb.target_response_time.maximum
aws.elb.target_response_time.p95
aws.elb.target_response_time.p99
aws.elb.un_healthy_host_count
aws.elb.un_healthy_host_count_deduped
aws.elb.un_healthy_host_count.maximum
aws.elb.un_healthy_host_count.minimum
*/

