
/* Metrics
aws.rds.active_transactions
aws.rds.aurora_binlog_replica_lag
aws.rds.aurora_replica_lag
aws.rds.aurora_replica_lag_maximum
aws.rds.aurora_replica_lag_minimum
aws.rds.bin_log_disk_usage
aws.rds.blocked_transactions
aws.rds.buffer_cache_hit_ratio
aws.rds.burst_balance
aws.rds.commit_latency
aws.rds.commit_throughput
aws.rds.cpucredit_balance
aws.rds.cpucredit_usage
aws.rds.cpuutilization
aws.rds.database_connections
aws.rds.ddllatency
aws.rds.ddlthroughput
aws.rds.deadlocks
aws.rds.delete_latency
aws.rds.delete_throughput
aws.rds.disk_queue_depth
aws.rds.dmllatency
aws.rds.dmlthroughput
aws.rds.engine_uptime
aws.rds.free_local_storage
aws.rds.free_storage_space
aws.rds.freeable_memory
aws.rds.insert_latency
aws.rds.insert_throughput
aws.rds.login_failures
aws.rds.maximum_used_transaction_ids
aws.rds.network_receive_throughput
aws.rds.network_throughput
aws.rds.network_transmit_throughput
aws.rds.oldest_replication_slot_lag
aws.rds.queries
aws.rds.read_iops
aws.rds.read_latency
aws.rds.read_throughput
aws.rds.replica_lag
aws.rds.replication_slot_disk_usage
aws.rds.result_set_cache_hit_ratio
aws.rds.select_latency
aws.rds.select_throughput
aws.rds.swap_usage
aws.rds.total_storage_space
aws.rds.transaction_logs_disk_usage
aws.rds.transaction_logs_generation
aws.rds.update_latency
aws.rds.update_throughput
aws.rds.volume_bytes_used
aws.rds.volume_read_iops
aws.rds.volume_write_iops
aws.rds.write_iops
aws.rds.write_latency
aws.rds.write_throughput
/**/
