
# Look at existing integration dashboard


/* Metrics
mongodb.asserts.msgps
mongodb.asserts.regularps
mongodb.asserts.rolloversps
mongodb.asserts.userps
mongodb.asserts.warningps
mongodb.connections.available
mongodb.connections.current
mongodb.connections.totalcreated
mongodb.dbs
mongodb.extra_info.page_faultsps
mongodb.fsynclocked
mongodb.globallock.activeclients.readers
mongodb.globallock.activeclients.total
mongodb.globallock.activeclients.writers
mongodb.globallock.currentqueue.readers
mongodb.globallock.currentqueue.total
mongodb.globallock.currentqueue.writers
mongodb.globallock.totaltime
mongodb.locks.collection.acquirecount.exclusiveps
mongodb.locks.collection.acquirecount.intent_exclusiveps
mongodb.locks.collection.acquirecount.intent_sharedps
mongodb.locks.collection.acquirewaitcount.exclusiveps
mongodb.locks.collection.timeacquiringmicros.exclusiveps
mongodb.locks.database.acquirecount.exclusiveps
mongodb.locks.database.acquirecount.intent_exclusiveps
mongodb.locks.database.acquirecount.intent_sharedps
mongodb.locks.database.acquirecount.sharedps
mongodb.locks.database.acquirewaitcount.exclusiveps
mongodb.locks.database.acquirewaitcount.intent_exclusiveps
mongodb.locks.database.acquirewaitcount.intent_sharedps
mongodb.locks.database.acquirewaitcount.sharedps
mongodb.locks.database.timeacquiringmicros.exclusiveps
mongodb.locks.database.timeacquiringmicros.intent_exclusiveps
mongodb.locks.database.timeacquiringmicros.intent_sharedps
mongodb.locks.database.timeacquiringmicros.sharedps
mongodb.locks.global.acquirecount.exclusiveps
mongodb.locks.global.acquirecount.intent_exclusiveps
mongodb.locks.global.acquirecount.intent_sharedps
mongodb.locks.global.acquirecount.sharedps
mongodb.locks.global.acquirewaitcount.exclusiveps
mongodb.locks.global.acquirewaitcount.intent_exclusiveps
mongodb.locks.global.acquirewaitcount.intent_sharedps
mongodb.locks.global.timeacquiringmicros.exclusiveps
mongodb.locks.global.timeacquiringmicros.intent_exclusiveps
mongodb.locks.global.timeacquiringmicros.intent_sharedps
mongodb.locks.metadata.acquirecount.exclusiveps
mongodb.locks.oplog.acquirecount.intent_exclusiveps
mongodb.mem.bits
mongodb.mem.mapped
mongodb.mem.mappedwithjournal
mongodb.mem.resident
mongodb.mem.virtual
mongodb.metrics.cursor.open.notimeout
mongodb.metrics.cursor.open.pinned
mongodb.metrics.cursor.open.total
mongodb.metrics.cursor.timedoutps
mongodb.metrics.document.deletedps
mongodb.metrics.document.insertedps
mongodb.metrics.document.returnedps
mongodb.metrics.document.updatedps
mongodb.metrics.getlasterror.wtime.numps
mongodb.metrics.getlasterror.wtime.totalmillisps
mongodb.metrics.getlasterror.wtimeoutsps
mongodb.metrics.operation.scanandorderps
mongodb.metrics.operation.writeconflictsps
mongodb.metrics.queryexecutor.scannedps
mongodb.metrics.record.movesps
mongodb.metrics.repl.apply.batches.numps
mongodb.metrics.repl.apply.batches.totalmillisps
mongodb.metrics.repl.apply.opsps
mongodb.metrics.repl.buffer.count
mongodb.metrics.repl.buffer.maxsizebytes
mongodb.metrics.repl.buffer.sizebytes
mongodb.metrics.repl.network.bytesps
mongodb.metrics.repl.network.getmores.numps
mongodb.metrics.repl.network.getmores.totalmillisps
mongodb.metrics.repl.network.opsps
mongodb.metrics.repl.network.readerscreatedps
mongodb.metrics.repl.preload.docs.numps
mongodb.metrics.repl.preload.docs.totalmillisps
mongodb.metrics.repl.preload.indexes.numps
mongodb.metrics.repl.preload.indexes.totalmillisps
mongodb.metrics.ttl.deleteddocumentsps
mongodb.metrics.ttl.passesps
mongodb.network.bytesinps
mongodb.network.bytesoutps
mongodb.network.numrequestsps
mongodb.opcounters.commandps
mongodb.opcounters.deleteps
mongodb.opcounters.getmoreps
mongodb.opcounters.insertps
mongodb.opcounters.queryps
mongodb.opcounters.updateps
mongodb.opcountersrepl.commandps
mongodb.opcountersrepl.deleteps
mongodb.opcountersrepl.getmoreps
mongodb.opcountersrepl.insertps
mongodb.opcountersrepl.queryps
mongodb.opcountersrepl.updateps
mongodb.oplog.logsizemb
mongodb.oplog.timediff
mongodb.oplog.usedsizemb
mongodb.replset.health
mongodb.replset.replicationlag
mongodb.replset.state
mongodb.replset.votefraction
mongodb.replset.votes
mongodb.stats.avgobjsize
mongodb.stats.collections
mongodb.stats.datasize
mongodb.stats.filesize
mongodb.stats.indexes
mongodb.stats.indexsize
mongodb.stats.numextents
mongodb.stats.objects
mongodb.stats.storagesize
mongodb.uptime
mongodb.usage.commands.count
mongodb.usage.commands.time
mongodb.usage.getmore.count
mongodb.usage.getmore.time
mongodb.usage.insert.count
mongodb.usage.insert.time
mongodb.usage.queries.count
mongodb.usage.queries.time
mongodb.usage.readlock.count
mongodb.usage.readlock.time
mongodb.usage.remove.count
mongodb.usage.remove.time
mongodb.usage.total.count
mongodb.usage.total.time
mongodb.usage.update.count
mongodb.usage.update.time
mongodb.usage.writelock.count
mongodb.usage.writelock.time
mongodb.wiredtiger.cache.bytes_currently_in_cache
mongodb.wiredtiger.cache.failed_eviction_of_pages_exceeding_the_in_memory_maximumps
mongodb.wiredtiger.cache.in_memory_page_splits
mongodb.wiredtiger.cache.maximum_bytes_configured
mongodb.wiredtiger.cache.maximum_page_size_at_eviction
mongodb.wiredtiger.cache.modified_pages_evicted
mongodb.wiredtiger.cache.pages_currently_held_in_cache
mongodb.wiredtiger.cache.pages_evicted_by_application_threadsps
mongodb.wiredtiger.cache.pages_evicted_exceeding_the_in_memory_maximumps
mongodb.wiredtiger.cache.pages_read_into_cache
mongodb.wiredtiger.cache.pages_written_from_cache
mongodb.wiredtiger.cache.tracked_dirty_bytes_in_cache
mongodb.wiredtiger.cache.unmodified_pages_evicted
mongodb.wiredtiger.concurrenttransactions.read.available
mongodb.wiredtiger.concurrenttransactions.read.out
mongodb.wiredtiger.concurrenttransactions.read.totaltickets
mongodb.wiredtiger.concurrenttransactions.write.available
mongodb.wiredtiger.concurrenttransactions.write.out
mongodb.wiredtiger.concurrenttransactions.write.totaltickets
*/
