
/* Metrics
redash.celery.task_runtime.cleanup_query_results.95percentile
redash.celery.task_runtime.cleanup_query_results.avg
redash.celery.task_runtime.cleanup_query_results.count
redash.celery.task_runtime.cleanup_query_results.max
redash.celery.task_runtime.cleanup_query_results.median
redash.celery.task_runtime.cleanup_tasks.95percentile
redash.celery.task_runtime.cleanup_tasks.avg
redash.celery.task_runtime.cleanup_tasks.count
redash.celery.task_runtime.cleanup_tasks.max
redash.celery.task_runtime.cleanup_tasks.median
redash.celery.task_runtime.refresh_queries.95percentile
redash.celery.task_runtime.refresh_queries.avg
redash.celery.task_runtime.refresh_queries.count
redash.celery.task_runtime.refresh_queries.max
redash.celery.task_runtime.refresh_queries.median
redash.celery.task_runtime.refresh_schemas.95percentile
redash.celery.task_runtime.refresh_schemas.avg
redash.celery.task_runtime.refresh_schemas.count
redash.celery.task_runtime.refresh_schemas.max
redash.celery.task_runtime.refresh_schemas.median
redash.celery.task.cleanup_query_results.success
redash.celery.task.cleanup_tasks.success
redash.celery.task.count
redash.celery.task.refresh_queries.success
redash.celery.task.refresh_schemas.success
redash.celery.task.runtime.95percentile
redash.celery.task.runtime.avg
redash.celery.task.runtime.count
redash.celery.task.runtime.max
redash.celery.task.runtime.median
redash.db.data_sources.select.95percentile
redash.db.data_sources.select.avg
redash.db.data_sources.select.count
redash.db.data_sources.select.max
redash.db.data_sources.select.median
redash.db.organizations.select.95percentile
redash.db.organizations.select.avg
redash.db.organizations.select.count
redash.db.organizations.select.max
redash.db.organizations.select.median
redash.db.queries.select.95percentile
redash.db.queries.select.avg
redash.db.queries.select.count
redash.db.queries.select.max
redash.db.queries.select.median
redash.db.query_results.delete.95percentile
redash.db.query_results.delete.avg
redash.db.query_results.delete.count
redash.db.query_results.delete.max
redash.db.query_results.delete.median
redash.manager.outdated_queries
redash.manager.outdated_queries_lookup.95percentile
redash.manager.outdated_queries_lookup.avg
redash.manager.outdated_queries_lookup.count
redash.manager.outdated_queries_lookup.max
redash.manager.outdated_queries_lookup.median
redash.manager.seconds_since_refresh
redash.requests.redash.ping.get.95percentile
redash.requests.redash.ping.get.avg
redash.requests.redash.ping.get.count
redash.requests.redash.ping.get.max
redash.requests.redash.ping.get.median
*/
